import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Luku Safi Laundromat',
  keywords: ['laundromat', 'management', 'system', 'nextjs', 'react'],
  authors: [{ name: 'Kyole', url: 'https://kyole.com' }],
  creator: 'Kyole',
  openGraph: {
    title: 'Luku Safi Laundromat',
    description: 'A modern laundromat management system built with Next.js',
    url: 'https://luku-safi-laundromat.vercel.app',
    siteName: 'Luku Safi Laundromat',
    // images: [
    //   {
    //     url: 'https://luku-safi-laundromat.vercel.app/og-image.png',
    //     width: 1200,
    //     height: 630,
    //     alt: 'Luku Safi Laundromat OG Image',
    //   },
    // ],
    locale: 'en_US',
    type: 'website',
  },
  // robots: {
  //   index: true,
  //   follow: true,
  //   nocache: false,
  // },
  themeColor: '#ffffff',
  appleWebApp: {
    capable: true,
    title: 'Luku Safi Laundromat',
    statusBarStyle: 'default',
  },
  icons: {
    icon: '/favicon.ico',
    shortcut: '/favicon.ico',
    apple: '/apple-touch-icon.png',
    other: [
      {
        rel: 'manifest',
        url: '/site.webmanifest',
      },
    ],
  },
  viewport: 'width=device-width, initial-scale=1',
  formatDetection: {
    telephone: false,
  },
  colorScheme: 'light dark',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
